package basic.allEnums.skills;

public enum BaseSkillType {
    MAIN_BATTLE_EXPERIENCE, ARMOR_SKILL, HAND_TO_HAND_FIGHT_SKILL,
    ONE_HANDED_WEAPON_SKILL, TWO_HANDED_WEAPON_SKILL, SHIELD_BLOCK_SKILL
}
