package basic.allEnums.skills;

public enum TwoHandedWeaponSkillType {
    TWO_HANDED_SWORD_FIGHT_SKILL, TWO_HANDED_AXE_FIGHT_SKILL, TWO_HANDED_MACE_FIGHT_SKILL,
    TWO_HANDED_HAMMER_FIGHT_SKILL, SPEAR_FIGHT_SKILL, HALBERD_FIGHT_SKILL, STAFF_FIGHT_SKILL
}
